language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
install:
- pip install --upgrade pip setuptools wheel
- pip install -r தேவைகள்.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install ennikkai --no-index --find-links=./dist
script:
- cd சோதனைகள்
- coverage run -m unittest மூலம்
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: i9WTpQAP0QZZTuI/MR5dToW/ZgAtKAOUdmKZucapjkbi6xSa2efZBbGOCPQTpMk7oMx0jzpN0lHb5Xqk4utCA+Ip2fnE2h/DHAH2pYCgK88o5N5Zqhtm0e+SWulhim8C1jOGYxlgVxeKLhat9jsaLfqjICdmPtbLtZFFMmVVBFhv3YWLwwtbW4EiCUe5CsqgHHAF9cFv7mal5jqjSqh+D73QpK+aFJnXXqh42rj8YYERc1H5IpQmgST6DWr3CLBna3KD6mAnQ5ItOeTE4ZwIuTgTohnkqnpNJ4xmj4WvqP5/mUpH9r/fFYgz83AjgrbMVK0lTrXrKyk0CYKl9LwUTVkF6Lvnz7OmuLTiyCrnwzqDPUCnFDUluT/h9FVF9DcQC75QfuYne6jCUtpv7QtLWS+5L0xPd4KxPNO4fLoPA/h3l1pX8/xXqtrCeA88cELgfpG6/sqeVb/SUOKMALjnlSVLxvCMBm4WAQlXI1uyJVUoNEBrzE9CzyhPJz4/kbZCZgw5P/c38BDXkl7Mt9Rs4oyQCVqo+mKBUOhGYiLYUjkMYPDfeFteZTW/hLz+n7Q3uPAI0lrDxRU1fILiSVHtUEgvGlLjEJfqUh4jTlC6hjh6zryOx8Cddddh8iA5pGu7L3ejvnQbaJzsQidmPIWvmXJtywoSJYz8mRXT360eyC0=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
