language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
install:
- pip install --upgrade pip setuptools wheel
- pip install -r தேவைகள்.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install ennikkai --no-index --find-links=./dist
script:
- cd சோதனைகள்
- coverage run -m unittest மூலம்
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: vnPcDNv7LeLNha4gwmgrBhWeFgsiMUXsP2lqKFPg21CFyK7q+GKzdS1JfqdgGwGFERh64/pTRsP+xlb5wxfHqvizmJfg4o/hNzpTx7p9QjzlR7PjDUir59hN2fW4ri+EarUFs0iP5Lc1HkOpKqKfmfCLyz14wgN6niI/Tnl+vCwlPmzyu6HdgH1H9RCe+e7Ql3K0W2LqeaPGno4bFPU4iHe+ZdAnVRhlr4QiVAqeQbE1ch6GCkjtR7avaU5X+Y/brhtjoaes+tHftHxt5YeaOxcp+c7RYZ5pLx63wmRXN5ynYJ3nCwMqJYcH8JC1SO2g2pRa7XjwAFm3X6hHeq0tWTk8EPrb40+Tpn493Pu/DLDL+biA0aRqK0E5NwatqAhW5Iks+7qqOQj5L8W6CKTzesnwh7heTS2UxFK46mRAKkTvmj+SeWOZUMQeIAfqivSqcaXsmPdwH3OacL/yMmLPVPhJ624qphS35rd6PkTcQ1dVVj0YMDjPCHmPHO9pQgrEF3pqbOxK9RWXKUJKQmLX35NPmk7Uv0VmoDwjkga+we6mFWDPYcKlGjXPg6jWvdi5y9g1ohgeuSmlUi2C7b8f+TeOU8+atxLQQj2Fd9ceoSppqDMU0J8zTC8/OVas2XaAiMYPYCjL1EQoq5phbs4/R0mbf1lF/NqFLhLRVq+hbFY=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
