language: python

matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6

install:
- pip install --upgrade pip setuptools wheel
- pip install -r தேவைகள்.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install ennikkai --no-index --find-links=./dist
- rm -r எண்ணிக்கை

script:
- cd சோதனைகள்
- coverage run -m unittest மூலம்

after_success:
- coveralls --rcfile=.coveragerc
- codecov

deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: fZ5PkJH+lGdeo4tCSc3UWuZgGmK9/S/t8OHpL8SpPBACbSZLqfEC0mLYcbliG0r2rwsMc6XrVl08FcVSMvnL3IFB95LCLT+R4BpnVIVSt+x3+1AhnyukfMuQUNXgmDwy6BjDF7YXPvKuloWfJH7rt1ywmxfxEewAnggIZ4nEwed/Ke734+6Fmd92rpeUsqm0/sBIeypc/GpSm61r5wfK4B6caMJhjKCq6sEyXV5PQmKrC/IhObLI2S0cuyXo8NO0nOZ1L0j8cf5we8a+m82MdPDtvcnPzAR9kXcxU9bvhWV12FtF7bqegYkNE0LlGE2QGDqAcLf2hCdgi05boSd24e5Dar8/gqJTzbzIDbXLo798IGTfIAVIsXO1iexhV3DyfYuXsJzq7u36xt4mso5xFBPyJGmXZR11mSreE14cPov05EGLea1aK7mzvi9ti3/ayTaVD2gmedmQR9lVvXLU3raxHWxSDFUlwhzyxq9+nuqRroG/BatpNxOnLm22qLZjUnZnLkyt+l4bhG8V7a3dL5jNOVsr22eJyxT2DfdbAdCuPVkaD4WVhd+CBU5EdT/fGkHAyrfsbpaay2gUBadgMiSI4EP/TRPzrdQHFmYUYpKyxYVokzzQe4Ftac+Jwkeoo1TxcUhWaZpYyxLnD53wgTcHWM0bxxVpakjDN4JOz2g=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true