language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
install:
- pip install --upgrade pip setuptools wheel
- pip install -r தேவைகள்.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install ennikkai --no-index --find-links=./dist
script:
- cd சோதனைகள்
- coverage run -m unittest மூலம்
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: M2Gb934arV6S5FDMOI0tv5oxP6kwPZ+SVUmer9A98MLWoxq4kwa1vKm4n7GDGSCd+3smkWy9RnEe5lcRSYepTcoH7RGXh+LFS3QGU5qt3sVVZ3EjVHJZSvAU8YAo3mLI48zjDDOyT8JUOu2Tu2ULAW+1HcqzDi+MRJw0D3ACV2b/1bhFmpDLuQeUORDrFF6+ctqMtSnrwLZkgVJz/a0NwrwoPTU3d+4ZZbBj28/rt9eF8BPkoCJ90EAUhuYsuyRMDm9jB/xZYK55O3sUim1bpeLF8xmr7rg+bFOshe3GX1kVHFQvsyMkOI1Xuen/OBTJ8UzcKru2DZ5MHFega5K9JToMPRYYB+9amq9bZjmQd2gB/ng8oCeMNb6FGMo9g4mvg5dxMYDY5SV3I1dKr4JW51dnOfkcwU5bXkiLzd51Due4mZ0WD8PVpBwskvPMfk3b+vYX0GC08t6d8+CJ0SAz+2A0XgMuMux07OJjOndWqbUC7J/xbXOE5K6HdKA34BHD8ZpNiFLmjef3Iyc+0Sr3C2OxCO3gDINuRYAJqjyOx3z5fAWAY9If4kf2soe68aMOMb4qE96FcCkH4Ww6IkTvfMiPTs07Siy1a+9XEZV+AmRRhWV/RUlQPypOPs+Qm/x1yVFiq1YRnKuc5ScLu/xpTIlgJax+lxtjYDZmBYtdTE8=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
