language: python
python:
- "3.6"

os:
- linux

install:
- pip install --upgrade pip setuptools wheel
- pip install -r தேவைகள்.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install ennikkai --no-index --find-links=./dist
- rm -r ennikkai

script:
- cd சோதனைகள்
- coverage run -m unittest

after_success:
- coveralls --rcfile=.coveragerc
- codecov
