environment:

  matrix:

  - PYTHON: "C:\\Python36-x64"

install:
- "set PATH=%PATH%;%PYTHON%\\Scripts"
- "%PYTHON%\\python.exe -m pip install --upgrade pip"
- "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
- "%PYTHON%\\python.exe -m pip install --upgrade wheel"
- "%PYTHON%\\python.exe -m pip install nose"
- "%PYTHON%\\python.exe -m pip show pip"
- "%PYTHON%\\python.exe -m pip show wheel"
- "%PYTHON%\\python.exe -m pip show setuptools"
- "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: false

test_script:
- "nosetests"

after_test:
- "%PYTHON%\\python.exe setup.py bdist_wheel"