environment:

  matrix:

  - PYTHON: "C:\\Python36-x64"

install:
- "set PATH=%PATH%;%PYTHON%\\Scripts"
- "%PYTHON%\\python.exe -m pip install --upgrade pip"
- "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
- "%PYTHON%\\python.exe -m pip install --upgrade wheel"
- "%PYTHON%\\python.exe setup.py -q install"

build: false

test_script:
- "%PYTHON%\\python.exe -m unittest"
